from __future__ import annotations

import html
import json
from typing import Any


CSS = """
:root {
  color-scheme: light;
  --bg: #f6f8fb;
  --surface: #ffffff;
  --surface-2: #eef2f7;
  --text: #182230;
  --muted: #5d6b7c;
  --line: #d8dee8;
  --allow: #087f5b;
  --review: #a15c00;
  --deny: #c92a2a;
  --info: #1c5f9f;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font: 14px/1.5 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
main { max-width: 1180px; margin: 0 auto; padding: 28px 20px 48px; }
header { border-bottom: 1px solid var(--line); padding-bottom: 18px; margin-bottom: 20px; }
.eyebrow { color: var(--muted); text-transform: uppercase; letter-spacing: .08em; font-size: 12px; font-weight: 700; }
h1 { margin: 4px 0 6px; font-size: 36px; line-height: 1.05; }
h2 { margin: 30px 0 12px; font-size: 22px; }
h3 { margin: 0 0 8px; font-size: 16px; }
.grid { display: grid; grid-template-columns: repeat(12, 1fr); gap: 12px; }
.card { border: 1px solid var(--line); background: var(--surface); border-radius: 8px; padding: 16px; }
.span-3 { grid-column: span 3; } .span-4 { grid-column: span 4; } .span-6 { grid-column: span 6; } .span-12 { grid-column: span 12; }
.metric { font-size: 28px; font-weight: 800; margin-top: 2px; }
.muted { color: var(--muted); }
.badge { display: inline-flex; align-items: center; border-radius: 999px; padding: 3px 9px; font-weight: 800; border: 1px solid currentColor; background: var(--surface); }
.badge.allow { color: var(--allow); } .badge.review { color: var(--review); } .badge.deny { color: var(--deny); }
.badge.info, .badge.unknown { color: var(--info); }
.kv { display: grid; grid-template-columns: 170px 1fr; gap: 7px 14px; }
.kv div:nth-child(odd) { color: var(--muted); }
.table { width: 100%; border-collapse: collapse; }
th, td { padding: 10px 12px; border-bottom: 1px solid var(--line); text-align: left; vertical-align: top; }
th { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .06em; }
tbody tr:nth-child(even) td { background: #fafbfd; }
.code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; word-break: break-all; }
.chips { display: flex; flex-wrap: wrap; gap: 6px; }
.chip { border: 1px solid var(--line); background: var(--surface-2); color: var(--muted); padding: 3px 8px; border-radius: 999px; font-size: 12px; }
.reason { border-left: 3px solid var(--info); }
.reason.high { border-color: var(--deny); } .reason.medium { border-color: var(--review); }
pre { white-space: pre-wrap; background: #f1f4f8; border: 1px solid var(--line); padding: 12px; border-radius: 8px; overflow: auto; }
footer { margin-top: 32px; color: var(--muted); font-size: 13px; }
@media (max-width: 840px) { .span-3,.span-4,.span-6 { grid-column: span 12; } .kv { grid-template-columns: 1fr; } }
"""


def render_dependency_passport(document: dict[str, Any]) -> str:
    decision = str(document.get("decision") or "unknown")
    counts = document.get("counts") or {}
    diff = document.get("diff") or {"summary": {}, "added": [], "removed": [], "changed": []}
    permit = document.get("permit") or None
    html_parts = [
        "<!doctype html>",
        "<html lang='en'><head><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        f"<title>Palsy Passport - {_e(document.get('project') or 'dependency admission')}</title>",
        f"<style>{CSS}</style></head><body><main>",
        _header(document, decision),
        "<section class='grid'>",
        _metric("Allowed", counts.get("allow", 0), "allow"),
        _metric("Review", counts.get("review", 0), "review"),
        _metric("Denied", counts.get("deny", 0), "deny"),
        _metric("Dependencies", document.get("dependency_count", 0), "info"),
        "</section>",
        _build_admission(document, permit),
        _dependency_diff(diff),
        _explanations(document.get("explanations") or []),
        _autopsies(document.get("autopsies") or []),
        _inventory(document.get("items") or []),
        _permit(permit),
        "<footer>Generated by Palsy Passport. No permit, no build.</footer>",
        "</main></body></html>",
    ]
    return "\n".join(part for part in html_parts if part)


def _header(document: dict[str, Any], decision: str) -> str:
    return f"""
<header>
  <div class='eyebrow'>Palsy Passport</div>
  <h1>Dependency admission report</h1>
  <p class='muted'>{_e(document.get('status') or '')}</p>
  <p><span class='badge {decision}'>{_e(decision.upper())}</span></p>
</header>
"""


def _metric(label: str, value: Any, kind: str) -> str:
    return f"<div class='card span-3'><div class='muted'>{_e(label)}</div><div class='metric'><span class='badge {kind}'>{_e(value)}</span></div></div>"


def _build_admission(document: dict[str, Any], permit: dict[str, Any] | None) -> str:
    permit_id = permit.get("id") if permit else "not issued"
    return f"""
<h2>Build Admission</h2>
<section class='card'>
  <div class='kv'>
    <div>Project</div><div>{_e(document.get('project'))}</div>
    <div>Environment</div><div>{_e(document.get('environment'))}</div>
    <div>Lockfile</div><div>{_e(document.get('lockfile_name'))}</div>
    <div>Lockfile digest</div><div class='code'>{_e(document.get('lockfile_digest'))}</div>
    <div>Policy</div><div>{_e(document.get('policy_name'))} <span class='code'>{_e(str(document.get('policy_hash') or '')[:16])}</span></div>
    <div>Build permit</div><div class='code'>{_e(permit_id)}</div>
  </div>
</section>
"""


def _dependency_diff(diff: dict[str, Any]) -> str:
    summary = diff.get("summary") or {}
    added = diff.get("added") or []
    removed = diff.get("removed") or []
    changed = diff.get("changed") or []
    signals = diff.get("new_signals") or []
    return f"""
<h2>Dependency Diff</h2>
<section class='grid'>
  <div class='card span-3'><div class='muted'>Added</div><div class='metric'>{_e(summary.get('added', 0))}</div></div>
  <div class='card span-3'><div class='muted'>Removed</div><div class='metric'>{_e(summary.get('removed', 0))}</div></div>
  <div class='card span-3'><div class='muted'>Changed</div><div class='metric'>{_e(summary.get('changed', 0))}</div></div>
  <div class='card span-3'><div class='muted'>New signals</div><div class='metric'>{_e(summary.get('new_signals', 0))}</div></div>
  <div class='card span-12'><h3>New risk signals</h3><div class='chips'>{_chips(signals) or '<span class="muted">No new signals detected.</span>'}</div></div>
  <div class='card span-4'><h3>Added</h3>{_item_list(added)}</div>
  <div class='card span-4'><h3>Removed</h3>{_item_list(removed)}</div>
  <div class='card span-4'><h3>Changed</h3>{_changed_list(changed)}</div>
</section>
"""


def _explanations(explanations: list[dict[str, Any]]) -> str:
    if not explanations:
        return "<h2>Explain This Decision</h2><section class='card'><p class='muted'>No review or deny reasons were emitted.</p></section>"
    cards = []
    for explanation in explanations:
        cards.append(
            f"""
<div class='card span-6 reason {_e(explanation.get('severity'))}'>
  <h3>{_e(explanation.get('title'))}</h3>
  <p><strong>Reason:</strong> {_e(explanation.get('reason'))}</p>
  <p><strong>Why Palsy cares:</strong> {_e(explanation.get('why'))}</p>
  <p><strong>Suggested fix:</strong> {_e(explanation.get('fix'))}</p>
  {_policy_hint(explanation)}
</div>
"""
        )
    return "<h2>Explain This Decision</h2><section class='grid'>" + "\n".join(cards) + "</section>"


def _autopsies(autopsies: list[dict[str, Any]]) -> str:
    interesting = [a for a in autopsies if a.get("decision") in {"review", "deny"} or a.get("risk_signals")]
    if not interesting:
        interesting = autopsies[:6]
    cards = []
    for autopsy in interesting[:12]:
        identity = autopsy.get("identity") or {}
        anatomy = autopsy.get("anatomy") or {}
        cards.append(
            f"""
<div class='card span-6'>
  <h3>{_e(autopsy.get('key'))}</h3>
  <p><span class='badge {_e(autopsy.get('decision'))}'>{_e(str(autopsy.get('decision') or '').upper())}</span></p>
  <div class='kv'>
    <div>Filename</div><div class='code'>{_e(identity.get('filename'))}</div>
    <div>Digest</div><div class='code'>{_e(identity.get('digest'))}</div>
    <div>Files</div><div>{_e(anatomy.get('file_count'))}</div>
    <div>Uncompressed bytes</div><div>{_e(anatomy.get('total_uncompressed_size'))}</div>
  </div>
  <p class='muted'>Risk signals</p>
  <div class='chips'>{_chips(autopsy.get('risk_signals') or []) or '<span class="muted">No explicit signal flags.</span>'}</div>
  <p class='muted'>Reasons</p>
  {_reasons(autopsy.get('reasons') or [])}
</div>
"""
        )
    return "<h2>Artefact Autopsy</h2><section class='grid'>" + "\n".join(cards) + "</section>"


def _inventory(items: list[dict[str, Any]]) -> str:
    rows = []
    for item in items:
        rows.append(
            "<tr>"
            f"<td class='code'>{_e(item.get('key'))}</td>"
            f"<td><span class='badge {_e(item.get('decision'))}'>{_e(item.get('decision_label'))}</span></td>"
            f"<td>{_e(item.get('severity'))}</td>"
            f"<td class='code'>{_e(item.get('digest'))}</td>"
            f"<td>{_e('; '.join(item.get('reasons') or []))}</td>"
            "</tr>"
        )
    return "<h2>Full Inventory</h2><section class='card'><table class='table'><thead><tr><th>Artefact</th><th>Decision</th><th>Severity</th><th>Digest</th><th>Reasons</th></tr></thead><tbody>" + "\n".join(rows) + "</tbody></table></section>"


def _permit(permit: dict[str, Any] | None) -> str:
    if not permit:
        return "<h2>Signed Permit</h2><section class='card'><p class='muted'>No build permit was issued for this run.</p></section>"
    return f"<h2>Signed Permit</h2><section class='card'><pre>{_e(json.dumps(permit, indent=2, sort_keys=True, default=str))}</pre></section>"


def _item_list(items: list[dict[str, Any]]) -> str:
    if not items:
        return "<p class='muted'>None.</p>"
    rows = []
    for item in items[:20]:
        rows.append(
            f"<li><span class='code'>{_e(item.get('key'))}</span> "
            f"<span class='badge {_e(item.get('decision'))}'>{_e(item.get('decision'))}</span></li>"
        )
    return "<ul>" + "".join(rows) + "</ul>"


def _changed_list(items: list[dict[str, Any]]) -> str:
    if not items:
        return "<p class='muted'>None.</p>"
    rows = []
    for item in items[:20]:
        before = item.get("before") or {}
        after = item.get("after") or {}
        rows.append(
            f"<li><span class='code'>{_e(item.get('key'))}</span><br>"
            f"<span class='muted'>{_e(before.get('decision'))} to {_e(after.get('decision'))}</span></li>"
        )
    return "<ul>" + "".join(rows) + "</ul>"


def _policy_hint(explanation: dict[str, Any]) -> str:
    hint = explanation.get("policy_hint")
    return f"<p><strong>Policy knob:</strong> <span class='code'>{_e(hint)}</span></p>" if hint else ""


def _reasons(reasons: list[str]) -> str:
    if not reasons:
        return "<p class='muted'>No explicit reasons.</p>"
    return "<ul>" + "".join(f"<li>{_e(reason)}</li>" for reason in reasons) + "</ul>"


def _chips(values: list[Any]) -> str:
    return "".join(f"<span class='chip'>{_e(value)}</span>" for value in values)


def _e(value: Any) -> str:
    if value is None:
        return ""
    return html.escape(str(value), quote=True)
